// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sites.sql

package models

import (
	"context"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
  url
) VALUES (
  $1
)
RETURNING id, url, created_at
`

func (q *Queries) CreateSite(ctx context.Context, url string) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, url)
	var i Site
	err := row.Scan(&i.ID, &i.Url, &i.CreatedAt)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, url, created_at FROM sites
ORDER BY id
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(&i.ID, &i.Url, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
